### ISSUE TITLE
Don't use prototype

### ISSUE THREAD

**Issue by donaldpipowitch** [leonardiwagner/z#4]
It would be better to use

```
var matches = require('z')

var myReverse = list => {
  return matches(list,  // first param for `matches` is an Array, String, etc.
    ()           => [], 
    (head, tail) => myReverse(tail).concat(head)
  )
}

myReverse([1, 2, 3, 4, 5]) //[5, 4, 3, 2, 1])
```

or

```
var matches = require('z')

var myReverse = list => {
  return matches(list)(  // `matches` returns a function to use patterns
    ()           => [], 
    (head, tail) => myReverse(tail).concat(head)
  )
}

myReverse([1, 2, 3, 4, 5]) //[5, 4, 3, 2, 1])
```

instead of

```
require('z')

var myReverse = list => {
  return list.matches (  // uses prototype
    ()           => [],
    (head, tail) => 
  )
}

myReverse([1, 2, 3, 4, 5]) //[5, 4, 3, 2, 1])
```

**Comment by leonardiwagner** [comment]
@donaldpipowitch , why do you think it's better? 

The current syntax was based on [Scala match.](http://docs.scala-lang.org/tutorials/tour/pattern-matching.html)

**Comment by donaldpipowitch** [comment]
@leonardiwagner Changing `prototype` is [dangerous](https://www.nczonline.net/blog/2010/03/02/maintainable-javascript-dont-modify-objects-you-down-own/).

Another way to solve this could be [`::` function bind syntax](http://babeljs.io/blog/2015/05/14/function-bind/), but this is experimental.

```
var matches = require('z')

var myReverse = list => {
  return list::matches (  // function bind syntax
    ()           => [],
    (head, tail) => 
  )
}

myReverse([1, 2, 3, 4, 5]) //[5, 4, 3, 2, 1])
```

**Comment by leonardiwagner** [comment]
@donaldpipowitch It's a bit controversial :smile: , I understand why libraries like underscore and lodash don't want to change prototype, since they aim a great mass of projects (even legacy ones) where changing the prototype of existing objects will be really bad.

I suppose that a lot of people prefer to write and read `list.map(f)` instead `_.map(list, f)`  , and since **z** is aimed for a smaller group, I'd like to take some risk for something pleasurable to use

Or at least, we can make a way to turn this optional, do you agree on something?

**Comment by donaldpipowitch** [comment]
> I suppose that a lot of people prefer to write and read list.map(f) instead _.map(list, f)

Definitely. That's why I'm really looking forward to `::`.

It's your library, you can decide. :) But I wouldn't change `prototype` even if this library is aimed for a smaller group. Say you make some demos now, it would be sad if they break in some years because a native `matches ` method will be implemented.

**Comment by leonardiwagner** [comment]
Hey @donaldpipowitch , just for the records, even thought I still believe in my personal opinion, the community feedback was same of yours, and since I want to make this not * mine * project, I did your suggested change, the 2nd layout:

```javascript
matches(1)(
  (x = 2)      => console.log(`number 2 is the best!!!`),
  (x = Number) => console.log(`number ${x} is not that good`),
  (x = Date)   => console.log(`blaa.. strings are awful!`)
)
``` 

This will be changed at `1.0.0` version which I plan to release soon, I'm already updating the docs on master, thanks for your collaboration!

**Comment by donaldpipowitch** [comment]
Cool, thank you for the update.
